name: Keep Alive

on:
  schedule:
    # 每月 1 号凌晨 0 点运行 (彻底避开你跑股票数据的时间)
    - cron: '0 3 1 * *'
  # 保留手动触发按钮，方便随时测试
  workflow_dispatch:

# ⚠️ 关键设置：赋予机器人写入代码库的权限，否则它无法打卡
permissions:
  contents: write

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Keep Alive Action
        uses: gautamkrishnar/keepalive-workflow@v1
