name: US Stock Daily Report - Test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run_report_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run report in test mode
        env:
          SEND_EMAIL: "false"
        run: python market_report.py
